### ISSUE TITLE
这种新键盘介绍的不够详细啊

### ISSUE THREAD

**Issue by Just2co** [ShionAt/Keys#3]
主键区貌似精简到了3排，而且每个键位都有几个输入值，而且很多数学运算符号，但究竟如何牛叉还是没看懂！估计专门为程序员设计的吧。

**Comment by ShionAt** [comment]
介绍里面说的很清楚了，等发售日会有更详细的

**Comment by Just2co** [comment]
@ShionAt 我的建议，键盘上加多颗麦克风，组成降噪阵列，现在手机上语音输入非常流行，科大讯飞语音识别结果非常高，这样的键盘配上语音输入法就避免手工敲击输入了

**Comment by ShionAt** [comment]
@Just2co 键盘是人类跟机器对话的唯一可靠的方式，加个麦克风简单，但我不考虑研发语音识别，让别人做好了

**Comment by Just2co** [comment]
支持，等发售日会有更详细的说明，防止提前介绍的过于详细被别人抄袭了创意！
